package net.xalcon.torchasm;

import com.google.common.eventbus.EventBus;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;

public class TorchDummyCore extends DummyModContainer
{
    public TorchDummyCore()
    {
        super(new ModMetadata());
        ModMetadata md = getMetadata();
        md.autogenerated = true;
        md.modId = "torchcore";
        md.name = md.description = "torchcore tweak";
        md.version = "@VERSION@";
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {

        bus.register(this);
        return true;
    }
}
