# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build
run-name: Gradle Build ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag to deploy'
        type: string
        default: "latest"

env:
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: download-release-asset
        name: Download release assets
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ github.event.inputs.release_tag }}
          file: torchmaster-fabric-${{ github.event.inputs.release_tag }}.jar
          target: release.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Curseforge
        id: publish_curseforge
        if: ${{ !cancelled() && steps.gradle_build.outcome == 'success' && github.event.inputs.deploy_curseforge == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: "254268"
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: ${{ steps.gradle_build.outputs.artifactfullname }}
          name: torchmaster-${{ steps.gradle_build.outputs.artifactversion }}
          version: ${{ steps.gradle_build.outputs.artifactversion }}
          version-type: ${{ steps.gradle_build.outputs.releasetype }}
          changelog-file: changelog.md
          loaders: forge
          game-versions: ${{ steps.gradle_build.outputs.mcversion }}
          java: ${{ env.JAVA_VERSION }}